# argo application for sample1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fllaca/argocd-examples"
    targetRevision: dev
    path: helm-monorepo/root
    helm:
      parameters:
      - name: argoApps.version
        value: $ARGOCD_APP_SOURCE_TARGET_REVISION
      valuesObject:
        sample1:
          image:
            tag: 1.19.10

  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
