# argo application for sample1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/image-updater-git-creds
    argocd-image-updater.argoproj.io/image-list: sample1=nginx:~1.19
    argocd-image-updater.argoproj.io/sample1.helm.image-name: sample1.image.repository
    argocd-image-updater.argoproj.io/sample1.helm.image-tag: sample1.image.tag
spec:
  project: default
  source:
    repoURL: "https://github.com/fllaca/argocd-examples"
    targetRevision: dev
    path: helm-monorepo/root
    helm:
      parameters:
      - name: argoApps.version
        value: $ARGOCD_APP_SOURCE_TARGET_REVISION

  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
